### ISSUE TITLE
[Models] Os models não estão contemplados outros estados de tarefas.

### ISSUE THREAD

**Issue by eowfenth** [Igor-ti/node-app#6]
Como a ideia foi uma estrutura de aplicativo de atividades a fazer, faz sentido termos algumas campos como:

```
Todo: {
  id: uuid,
  title: Date,
  description: Date,
  authorId: Date,
  createdAt: Date,
  deletedAt: Date,
  completedAt: Date
},
```

Eu não sei se o MongoDB possui suporte a uuid como id de referência, eu imagino que sim. Eu passaria a utilizar alguma dessas libs para utilizar (bcryptjs / bcrypt);

Além disso, eu alteraria os métodos para permitir que marque uma tarefa como concluida e refaça por exemplo.

Se você quiser ir além, você poderia colocar uma pontuação associada ao ato de completar ela.

**Comment by Igor-ti** [comment]
não consegui colocar o id como uuid, inseri como string mas continuarei buscando. os restos dos dados eu agreguei. será necessario criar uma classe de author? correto?
